spring.application.name=grafana
source.grafana.url=https://agoncillo.grafana.crowncork.com
source.grafana.token=glsa_SSsss3k8zILrfAO6yUrFOMMkvhO59PkM_43c6783a
destination.grafana.url=https://osmaniye.grafana.crowncork.com
destination.grafana.token=glsa_IAtqFfB2aHPMtJ6VzCQnoluqjtFJ4zbu_22de78b7
source.grafana.datasource.uid=cfid33to182kgd
destination.grafana.datasource.uid=cf3pgaui6cav4d

grafana.namespace=default

