spring.application.name=grafana
source.grafana.url=https://agoncillo.grafana.crowncork.com
source.grafana.token=
destination.grafana.url=https://osmaniye.grafana.crowncork.com
destination.grafana.token=
source.grafana.datasource.uid=cfid33to182kgd
destination.grafana.datasource.uid=cf3pgaui6cav4d

grafana.namespace=default

